(define-module (my-packages)
  #:export (emacs-packages))

(use-modules (guix packages)
             (guix git-download)
             (gnu packages emacs-xyz))


(use-package-modules emacs)

(define emacs-packages
  (packages->manifest
 (list emacs
       emacs-guix
       emacs-exwm
       emacs-xelb
       emacs-exwm-edit
       emacs-hydra
       emacs-transient
       emacs-howm
       emacs-emms
       emacs-circe
       emacs-pdf-tools
       emacs-elfeed
       emacs-dumb-jump
       emacs-json-mode
       emacs-web-beautify
       emacs-web-mode
       emacs-async
       emacs-dash
       emacs-f
       emacs-s
       emacs-ht
       emacs-a
       emacs-request
       emacs-exec-path-from-shell
       emacs-desktop-environment
       emacs-all-the-icons
       emacs-which-key
       emacs-discovery-my-major
       emacs-helpful
       emacs-better-defaults
       emacs-hlinum
       emacs-visual-fill-column
       emacs-ace-window
       emacs-transpose-frame
       emacs-dired-hacks
       emacs-dired-rsync
       emacs-avy
       emacs-goto-chg
       emacs-expand-region
       emacs-smartparens
       emacs-edit-indirect
       emacs-flycheck
       emacs-wgrep
       emacs-anzu
       emacs-counsel-projectile
       emacs-ivy
       emacs-ivy-rich
       emacs-smex
       emacs-company
       emacs-company-quickhelp
       emacs-prescient
       emacs-crux
       emacs-keyfreq
       emacs-elmacro
       emacs-projectile
       emacs-ibuffer-projectile
       emacs-magit
       emacs-git-timemachine
       emacs-gitpatch
       emacs-org
       emacs-org-contrib
       emacs-org-pomodoro
       emacs-markdown-mode
       emacs-nov
       emacs-scratch
       emacs-yasnippet
       emacs-yasnippet-snippets
       emacs-auto-yasnippet
       emacs-htmlize
       ))
      ;emacs-vlf
      ;emacs-super-save
      ;emacs-ivy-historian
      ;emacs-swiper
      ;emacs-counsel
      ;emacs-deadgrep
      ;emacs-ivy-xref
      ;emacs-ivy-hydra
      ;emacs-ivy-prescient
      ;emacs-historian
      ;emacs-flycheck-color-mode-line
      ;emacs-company-emoji
      ;emacs-company-try-hard
      ;emacs-company-prescient
      ;emacs-gist
      ;emacs-copy-as-format
      ;emacs-recentf
      ;emacs-hideshow
      ;emacs-outline
      ;emacs-bicycle
      ;emacs-org-cliplink
      ;emacs-org-download
      ;emacs-org-journal
      ;emacs-toc-org
      ;emacs-ox-gfm
      ;emacs-browse-kill-ring
      ;emacs-persistent-scratch
      ;emacs-unkillable-scratch
      ;dired-k
      ;dired-hide-dotfiles
      ;dired-imenu
      ;dired-hacks-utils
      ;dired-filter
      ;dired-avfs
      ;dired-open
      ;dired-narrow
      ;dired-subtree
      ;dired-collapse
      ;emacs-buffer-move
      ;emacs-windmove
      ;emacs-beacon
      ;emacs-doom-themes
      ;emacs-doom-modeline
      ;emacs-counsel
      ;emacs-gpastel
      ;emacs-boon
      ;emacs-objed
      ;emacs-hyperbole
      ;emacs-torus
