(use-modules (guix packages)
             (guix git-download)
             (gnu packages emacs-xyz))

(use-package-modules emacs)


(packages->manifest
 (list emacs
       emacs-a
;       emacs-all-the-icons-ivy
       emacs-anzu
       emacs-auto-yasnippet
       emacs-beacon
       emacs-better-defaults
       emacs-boon
       emacs-browse-kill-ring
       emacs-buffer-move
       emacs-bui
       emacs-circe
       emacs-company-emoji
       emacs-company-prescient
       emacs-company-quickhelp
       emacs-company-try-hard
       emacs-company
       emacs-copy-as-format
       emacs-counsel-projectile
       emacs-counsel
       emacs-crux
       emacs-deadgrep
       emacs-desktop-environment
       emacs-dired-avfs
       emacs-dired-collapse
       emacs-dired-filter
       emacs-dired-hide-dotfiles
       emacs-dired-imenu
       emacs-dired-k
       emacs-dired-narrow
       emacs-dired-open
       emacs-dired-rsync
       emacs-dired-subtree
       emacs-dired-hacks-utils
       emacs-discover-my-major
       emacs-doom-modeline
       emacs-doom-themes
       emacs-all-the-icons
       emacs-dumb-jump
       emacs-edit-indirect
       emacs-elfeed
       emacs-elmacro
       emacs-elpa-mirror
       emacs-emms
       emacs-eval-in-repl
       emacs-ace-window
       emacs-avy
       emacs-exec-path-from-shell
       emacs-expand-region
       emacs-exwm
       emacs-exwm-edit
       emacs-fancy-narrow
       emacs-flycheck-color-mode-line
       emacs-flycheck
       emacs-gist
       emacs-gh
       emacs-git-timemachine
       emacs-gitpatch
       emacs-goto-chg
       emacs-goto-last-change
       emacs-goto-last-point
       emacs-gpastel
       emacs-groovy-mode
       emacs-helpful
       emacs-elisp-refs
       emacs-hlinum
       emacs-howm
       emacs-htmlize
       emacs-hyperbole
       emacs-ibuffer-projectile
       emacs-ivy-historian
       emacs-flx
       emacs-historian
       emacs-ivy-hydra
       emacs-ivy-prescient
       emacs-ivy-rich
       emacs-ivy-xref
       emacs-js3-mode
       emacs-json-mode
       emacs-json-reformat
       emacs-json-snatcher
       emacs-kdeconnect
       emacs-logito
       emacs-loop
       emacs-magit
       emacs-git-commit
       emacs-makey
       emacs-markdown-mode
       emacs-marshal
       emacs-ht
       emacs-nov
       emacs-esxml
       emacs-ob-ipython
       emacs-dash-functional
       emacs-ob-restclient
       emacs-objed
       emacs-org-cliplink
       emacs-org-download
       emacs-org-journal
       emacs-org-plus-contrib
       emacs-org-pomodoro
       emacs-alert
       emacs-log4e
       emacs-gntp
       emacs-ox-gfm
       emacs-paradox
       emacs-hydra
       emacs-lv
       emacs-paredit
       emacs-pbcopy
       emacs-pdf-tools
       emacs-persistent-scratch
       emacs-persistent-soft
       emacs-list-utils
       emacs-pcache
       emacs-popup
       emacs-prescient
       emacs-projectile
       emacs-pkg-info
       emacs-epl
       emacs-request
       emacs-restclient
       emacs-scratch
       emacs-scss-mode
       emacs-shrink-path
       emacs-f
       emacs-smartparens
       emacs-smex
       emacs-spinner
       emacs-super-save
       emacs-swiper
       emacs-ivy
       emacs-tablist
       emacs-toc-org
       emacs-torus
       emacs-transient
       emacs-dash
       emacs-transpose-frame
       emacs-tree-mode
       emacs-undo-tree
       emacs-unkillable-scratch
       emacs-use-package-chords
       emacs-bind-chord
       emacs-key-chord
       emacs-use-package
       emacs-bind-key
       emacs-vlf
       emacs-volatile-highlights
       emacs-web-beautify
       emacs-web-mode
       emacs-wgrep
       emacs-which-key
       emacs-with-editor
       emacs-async
       emacs-with-simulated-input
       emacs-s
       emacs-writeroom-mode
       emacs-visual-fill-column
       emacs-xelb
       emacs-yasnippet-snippets
       emacs-yasnippet
       ))
